/**
 * Bake the registry manifest and every example's source into one module.
 *
 * The docs need two things off disk: `registry.json`, and the text of each
 * example file so the Code tab can show the same file that produced the
 * preview. Reading either at request time means `fs` in a server component,
 * which drags the whole repo into Next's file trace and depends on the build's
 * working directory — two things that behave differently on Vercel than they
 * do locally. Reading them here instead makes the app a pure bundle.
 *
 * Run by `predev`, `prebuild` and `pretypecheck`; the output is gitignored, so
 * it can never be stale relative to the registry.
 */
import fs from "node:fs/promises";
import path from "node:path";

const appDir = path.resolve(import.meta.dirname, "..");
const repoRoot = path.resolve(appDir, "../..");

/** Every `.tsx` under examples/, as slash-separated paths without extension. */
async function findExamples(dir: string, prefix = ""): Promise<string[]> {
  const entries = await fs.readdir(dir, { withFileTypes: true });
  const found: string[] = [];

  for (const entry of entries) {
    const child = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      found.push(...(await findExamples(child, `${prefix}${entry.name}/`)));
    } else if (entry.name.endsWith(".tsx")) {
      found.push(`${prefix}${entry.name.replace(/\.tsx$/, "")}`);
    }
  }

  return found.sort();
}

const registryJson = await fs.readFile(path.join(repoRoot, "registry.json"), "utf8");
const registry = JSON.parse(registryJson) as { items: { name: string }[] };

const examplesDir = path.join(appDir, "examples");
const names = await findExamples(examplesDir);

const sources: Record<string, string> = {};
for (const name of names) {
  const raw = await fs.readFile(path.join(examplesDir, `${name}.tsx`), "utf8");
  // The pragma is an artefact of documenting Vite components inside an App
  // Router app, not something a consumer copying this into their NUI needs.
  sources[name] = raw.replace(/^["']use client["'];?\s*\n+/, "").trimEnd();
}

const out = `// GENERATED by scripts/gen-data.ts — do not edit, do not commit.
import type { Registry } from "./registry-types";

export const registry: Registry = ${registryJson.trimEnd()};

export const exampleSources: Record<string, string> = ${JSON.stringify(sources, null, 2)};
`;

await fs.writeFile(path.join(appDir, "lib", "data.generated.ts"), out);

console.log(
  `gen-data: ${registry.items.length} registry items, ${names.length} examples`,
);
