/**
 * Generates registry/theme/9am-fonts.css from the woff2 files in
 * registry/theme/fonts/.
 *
 * Why base64: a shadcn registry item carries its files as strings inside JSON,
 * so binary woff2 cannot ride along. Embedding them as `data:` URIs keeps
 * `@9am/theme` a genuine one-command install with no second "now go fetch the
 * fonts" step for anyone to forget. The 240 KB of woff2 becomes ~328 KB of CSS,
 * which costs nothing meaningful in a FiveM NUI: everything is served off local
 * disk, so there is no network round-trip to trade away — only a one-time parse.
 *
 * The exception is an app with SEVERAL html entry points — notably one that
 * renders DUI textures, since every DUI is its own CEF instance and would
 * decode the whole payload again with no shared cache. Those should use
 * `bunx 9am-ui fonts` instead, which writes the woff2 files plus a linked
 * stylesheet the small entries can import.
 *
 * Run after changing anything under registry/theme/fonts/:
 *   bun run fonts
 */
import fs from "node:fs";
import path from "node:path";
import { FACES } from "./faces";

const FONT_DIR = path.join(import.meta.dir, "..", "registry", "theme", "fonts");
const OUT = path.join(import.meta.dir, "..", "registry", "theme", "9am-fonts.css");

const blocks = FACES.map(({ family, file, weight }) => {
  const abs = path.join(FONT_DIR, file);
  if (!fs.existsSync(abs)) throw new Error(`missing font file: ${file}`);
  const b64 = fs.readFileSync(abs).toString("base64");
  return `@font-face {
  font-family: '${family}';
  src: url(data:font/woff2;base64,${b64}) format('woff2');
  font-weight: ${weight};
  font-style: normal;
  font-display: swap;
}`;
});

const header = `/* --------------------------------------------------------------------------
   9AM UI — FONTS (Poppins body, Phudu display)
   GENERATED by scripts/build-fonts.ts. DO NOT EDIT BY HAND.
   Edit the woff2 files under registry/theme/fonts/ and re-run \`bun run fonts\`.
   -------------------------------------------------------------------------- */

`;

fs.writeFileSync(OUT, header + blocks.join("\n\n") + "\n");

const rawBytes = FACES.reduce((n, f) => n + fs.statSync(path.join(FONT_DIR, f.file)).size, 0);
console.log(
  `9am-fonts.css: ${FACES.length} faces, ${(rawBytes / 1024).toFixed(0)} KB woff2 -> ${(
    fs.statSync(OUT).size / 1024
  ).toFixed(0)} KB css`,
);
